Add githubcli aliases and functions

diff --git a/.config/shell/aliasrc b/.config/shell/aliasrc
--- a/.config/shell/aliasrc
+++ b/.config/shell/aliasrc
@@ -56,6 +56,15 @@ alias \
   weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
 
 # User created 
+
+## Functions
+install_jq() {
+    if ! command -v jq > /dev/null>&1; then
+        echo "jq not found. Installing jq..."
+        yay -S jq  # Use 'pacman -S jq' if you don't use yay
+    fi
+}
+
 ## General 
 alias \
   agora="date '+%Y-%m-%d_%Hh%Mm%Ss'" \
@@ -122,3 +131,7 @@ alias \
     gl='git log --all --graph --oneline --decorate' \
     gs='git status' \
     ga='git add .'
+  ### GitHub CLI
+  alias \
+    prl=get_pr_list_for_authenticated_user \
+    pr='gh pr view -c' \
